python src/train.py \
    --data_root data/mvtec_ad \
    --class_name capsule \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 384 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

python src/train.py \
    --data_root data/mvtec_ad \
    --class_name capsule \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 256 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=1 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name capsule \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 128 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=1 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name capsule \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 64 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results & 

export CUDA_VISIBLE_DEVICES=2 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name capsule \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 32 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=2 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name capsule \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 16 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=3 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name capsule \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 8 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

# wait until all background jobs are done
wait

export CUDA_VISIBLE_DEVICES=0 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name grid \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 384 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=0 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name grid \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 256 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=1 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name grid \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 128 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=1 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name grid \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 64 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results & 

export CUDA_VISIBLE_DEVICES=2 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name grid \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 32 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=2 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name grid \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 16 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=3 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name grid \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 8 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

wait

export CUDA_VISIBLE_DEVICES=0 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name pill \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 384 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=0 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name pill \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 256 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=1 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name pill \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 128 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=1 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name pill \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 64 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results & 

export CUDA_VISIBLE_DEVICES=2 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name pill \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 32 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=2 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name pill \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 16 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &

export CUDA_VISIBLE_DEVICES=3 &&
python src/train.py \
    --data_root data/mvtec_ad \
    --class_name pill \
    --num_normal_samples -1 \
    --ae_model conv_ae_sp1 \
    --ae_hidden_dim 384 \
    --bottleneck_dim 8 \
    --backbone_model pdn_small \
    --backbone_resume_path ./weights/teacher_small.pth \
    --feature_dim 384 \
    --feature_res 1 \
    --img_size 256 \
    --split train \
    --batch_size 8 \
    --num_epochs 100 \
    --lr 0.0001 \
    --momentum 0.9 \
    --weight_decay 0.05 \
    --optimizer adamw \
    --scheduler cosine \
    --grad_clip 1.0 \
    --seed 42 \
    --num_workers 1 \
    --device cuda \
    --log_interval 10 \
    --save_dir results &